Upd Actions

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -49,12 +49,15 @@ jobs:
             "$API_ENDPOINT/v3/monitors/$monitor_uuid/script" \
             -d "$script_payload"
 
-          if [[ "$response" -ge 400 && "$response" -le 404 ]]; then
-            echo "Error: Failed to update the Synthetic Monitor script for $file_path. HTTP Status: $response"
-              exit 1
-          fi 
-            
-          echo "Synthetic Monitor script for $file_path and monitor id $monitor_uuid updated successfully."       
+          if [ "$response_status" -ge 200 ] && [ "$response_status" -lt 300 ]; then
+            echo "Synthetic Monitor script for $file_path and monitor id $monitor_uuid updated successfully."
+          else
+            echo "Error: Failed to update the Synthetic Monitor script for $file_path (Monitor ID: $monitor_uuid)."
+            echo "HTTP Status Code: $response_status"
+            echo "Response Body:"
+            cat /tmp/monitor_update_response
+            exit 1
+          fi    
         }
 
         # Check if seleniumScriptTeacher.js was modified
