Update act file

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -2,6 +2,9 @@ name: Update New Relic Synthetic Monitor Scripts
 
 on:
   push:
+    branches:
+      - dev
+      - qa
     paths:
       - seleniumScriptTeacher.js
       - seleniumScriptStudent.js
@@ -14,10 +17,25 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v3
 
+    - name: Set environment variables based on branch
+      id: set-env
+      run: |
+        if [ "${{ github.ref_name }}" == "dev" ]; then
+          echo "env=dev" >> $GITHUB_ENV
+          echo "API_KEY=${{ secrets.NEW_RELIC_API_KEY }}" >> $GITHUB_ENV
+          echo "MONITOR_UUID_TEACHER=${{ secrets.NEW_RELIC_MONITOR_UUID_TEACHER_DEV }}" >> $GITHUB_ENV
+          echo "MONITOR_UUID_STUDENT=${{ secrets.NEW_RELIC_MONITOR_UUID_STUDENT_DEV }}" >> $GITHUB_ENV
+        elif [ "${{ github.ref_name }}" == "qa" ]; then
+          echo "env=qa" >> $GITHUB_ENV
+          echo "API_KEY=${{ secrets.NEW_RELIC_API_KEY }}" >> $GITHUB_ENV
+          echo "MONITOR_UUID_TEACHER=${{ secrets.NEW_RELIC_MONITOR_UUID_TEACHER_QA }}" >> $GITHUB_ENV
+          echo "MONITOR_UUID_STUDENT=${{ secrets.NEW_RELIC_MONITOR_UUID_STUDENT_QA }}" >> $GITHUB_ENV
+        else
+          echo "Error: Unsupported branch: ${{ github.ref_name }}"
+          exit 1
+        fi
+
     - name: Base64 encode and update scripts
-      env:
-        API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
-        API_ENDPOINT: https://synthetics.newrelic.com/synthetics/api
       run: |
         update_script() {
           local file_path="$1"
@@ -34,7 +52,7 @@ jobs:
           curl -v -X PUT \
             -H "Api-Key:$API_KEY" \
             -H 'Content-Type: application/json' \
-            "$API_ENDPOINT/v3/monitors/$monitor_uuid/script" \
+            "https://synthetics.newrelic.com/synthetics/api/v3/monitors/$monitor_uuid/script" \
             -d "$script_payload"
 
           if [ $? -ne 0 ]; then
@@ -48,11 +66,11 @@ jobs:
         # Check if seleniumScriptTeacher.js was modified
         if git diff --name-only HEAD^ HEAD | grep -q "seleniumScriptTeacher.js"; then
           echo "Updating seleniumScriptTeacher.js..."
-          update_script "./seleniumScriptTeacher.js" "${{ secrets.NEW_RELIC_MONITOR_UUID_TEACHER }}"
+          update_script "./seleniumScriptTeacher.js" "$MONITOR_UUID_TEACHER"
         fi
 
         # Check if seleniumScriptStudent.js was modified
         if git diff --name-only HEAD^ HEAD | grep -q "seleniumScriptStudent.js"; then
           echo "Updating seleniumScriptStudent.js..."
-          update_script "./seleniumScriptStudent.js" "${{ secrets.NEW_RELIC_MONITOR_UUID_STUDENT }}"
+          update_script "./seleniumScriptStudent.js" "$MONITOR_UUID_STUDENT"
         fi
